### ISSUE TITLE
Crash when planting Rubber trees in 2.1.2

### ISSUE THREAD

**Issue by SnappierSoap318** [CoolMineman/Plant-In-A-Jar#17]
Client log: 
[client.txt](https://github.com/CoolMineman/Plant-In-A-Jar/files/6560321/crash-2021-05-28_16.09.37-client.txt)

**Comment by enosich** [comment]
Hey Snappier! I'm gonna try and tackle this in my [fork](https://github.com/enosich/Plant-In-A-Jar). Feel free to assist if you'd like!

**Comment by mmagoo13** [comment]
Mod is also crashing for me with the Tech Reborn Rubber tree on 2.1.2

 15:02:09] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: Ticking block entity
	at net.minecraft.class_1937.method_18471(class_1937.java:521) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:176) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1556) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1021) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Could not find registered rubber tree feature!
	at techreborn.world.RubberSaplingGenerator.method_11430(RubberSaplingGenerator.java:45) ~[TechReborn-1.16-3.8.4+build.236.jar:?]
	at net.minecraft.class_2647.method_11431(class_2647.java:22) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2473.method_10507(class_2473.java:49) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at io.github.coolmineman.plantinajar.tree.TreeMan.genTree(TreeMan.java:48) ~[plantinajar-2.1.2.jar:?]
	at io.github.coolmineman.plantinajar.JarBlockEntity.method_16896(JarBlockEntity.java:124) ~[plantinajar-2.1.2.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:510) ~[intermediary-minecraft-1.16.5-client.jar:?]
	... 20 more

**Comment by Humblenovak** [comment]
any update on this?
