### ISSUE TITLE
1.17.1 Aether Reborn saplings trigger crash on planting

### ISSUE THREAD

**Issue by akoimeexx** [CoolMineman/Plant-In-A-Jar#21]
Tested in default world type as well as superflat void (after crash, world is unusable without modifying `level.dat` to to remove the block) to same effect. Tested with different Aether Reborn saplings, all replicate this issue.

Possible duplicate of issue #17 but not confirmed.

```
[23:28:04] [Render thread/INFO]: Stopping worker threads
[23:28:04] [Render thread/INFO]: Destroying pipeline OVERWORLD
[23:28:05] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: Ticking block entity
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:900) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:474) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:171) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1750) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1081) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2794.method_33730()" because "â˜ƒ" is null
	at net.minecraft.class_5868.<init>(class_5868.java:11) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5444.<init>(class_5444.java:19) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2988.method_13151(class_2988.java:28) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:58) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2647.method_11431(class_2647.java:28) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2473.method_10507(class_2473.java:49) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2473.doTheGrow(class_2473.java:517) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at io.github.coolmineman.plantinajar.tree.TreeMan.genTree(TreeMan.java:51) ~[plantinajar-2.2.2.jar:?]
	at io.github.coolmineman.plantinajar.JarBlockEntity.tick(JarBlockEntity.java:114) ~[plantinajar-2.2.2.jar:?]
	at io.github.coolmineman.plantinajar.JarBlock.lambda$getTicker$0(JarBlock.java:33) ~[plantinajar-2.2.2.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:886) ~[intermediary-minecraft-1.17.1-client.jar:?]
	... 22 more
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/4/21, 11:28 PM
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2794.method_33730()" because "â˜ƒ" is null
	at net.minecraft.class_5868.<init>(class_5868.java:11)
	at net.minecraft.class_5444.<init>(class_5444.java:19)
	at net.minecraft.class_2988.method_13151(class_2988.java:28)
	at net.minecraft.class_2975.method_12862(class_2975.java:58)
	at net.minecraft.class_2647.method_11431(class_2647.java:28)
	at net.minecraft.class_2473.method_10507(class_2473.java:49)
	at net.minecraft.class_2473.doTheGrow(class_2473.java:517)
	at io.github.coolmineman.plantinajar.tree.TreeMan.genTree(TreeMan.java:51)
	at io.github.coolmineman.plantinajar.JarBlockEntity.tick(JarBlockEntity.java:114)
	at io.github.coolmineman.plantinajar.JarBlock.lambda$getTicker$0(JarBlock.java:33)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:886)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941)
	at net.minecraft.class_1937.method_18471(class_1937.java:474)
	at net.minecraft.class_638.method_18116(class_638.java:171)
	at net.minecraft.class_310.method_1574(class_310.java:1750)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_5868.<init>(class_5868.java:11)
	at net.minecraft.class_5444.<init>(class_5444.java:19)
	at net.minecraft.class_2988.method_13151(class_2988.java:28)
	at net.minecraft.class_2975.method_12862(class_2975.java:58)
	at net.minecraft.class_2647.method_11431(class_2647.java:28)
	at net.minecraft.class_2473.method_10507(class_2473.java:49)
	at net.minecraft.class_2473.doTheGrow(class_2473.java:517)
	at io.github.coolmineman.plantinajar.tree.TreeMan.genTree(TreeMan.java:51)
	at io.github.coolmineman.plantinajar.JarBlockEntity.tick(JarBlockEntity.java:114)
	at io.github.coolmineman.plantinajar.JarBlock.lambda$getTicker$0(JarBlock.java:33)

-- Block entity being ticked --
Details:
	Name: plantinajar:plant_jar // io.github.coolmineman.plantinajar.JarBlockEntity
	Block: Block{plantinajar:plant_jar}
	Block location: World: (-2,-59,14), Section: (at 14,5,14 in -1,-4,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Block: Block{plantinajar:plant_jar}
	Block location: World: (-2,-59,14), Section: (at 14,5,14 in -1,-4,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:886)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941)
	at net.minecraft.class_1937.method_18471(class_1937.java:474)
	at net.minecraft.class_638.method_18116(class_638.java:171)
```

**Comment by akoimeexx** [comment]
On further examination of logfile from #17, I do not think this is the same issue.

**Comment by MSandro** [comment]
```
-- Block entity being ticked --
Details:
	Name: plantinajar:plant_jar // io.github.coolmineman.plantinajar.JarBlockEntity
	Block: Block{plantinajar:plant_jar}
	Block location: World: (-2982,82,-1970), Section: (at 10,2,14 in -187,5,-124; chunk contains blocks -2992,0,-1984 to -2977,255,-1969), Region: (-6,-4; contains chunks -192,-128 to -161,-97, blocks -3072,0,-2048 to -2561,255,-1537)
	Block: Block{plantinajar:plant_jar}
	Block location: World: (-2982,82,-1970), Section: (at 10,2,14 in -187,5,-124; chunk contains blocks -2992,0,-1984 to -2977,255,-1969), Region: (-6,-4; contains chunks -192,-128 to -161,-97, blocks -3072,0,-2048 to -2561,255,-1537)
	Block Entity NBT: {Items:[{Count:1b,Slot:0b,id:"the_aether:lavender_wisteria_sapling"},{Count:1b,Slot:1b,id:"minecraft:dirt"}],id:"plantinajar:plant_jar",seed:-1036018511408138815L,tickyes:600,x:-2982,y:82,z:-1970}
```
Same here! hope you can fix this soon, please.
