### ISSUE TITLE
Game crashes with "Inmis" (I need more inventory space!) mod installed

### ISSUE THREAD

**Issue by Avemado** [CoolMineman/Plant-In-A-Jar#9]
Have tried different Backpack mods and they've worked fine.
The issue arises once you place a Jar on top of a Hopper. For some reason the game just crashes at that point.
Here's the log for reference:

[crash-2020-11-05_04.03.54-server.txt](https://github.com/CoolMineman/Plant-In-A-Jar/files/5491731/crash-2020-11-05_04.03.54-server.txt)

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 11/5/20 4:03 AM
Description: Ticking block entity

java.lang.ExceptionInInitializerError
	at alexiil.mc.lib.attributes.item.mixin.HopperHooks.tryExtract(HopperHooks.java:87)
	at net.minecraft.class_2614.handler$zzp000$onExtract(class_2614.java:538)
	at net.minecraft.class_2614.method_11241(class_2614.java)
	at net.minecraft.class_2614.method_11249(class_2614.java:109)
	at net.minecraft.class_2614$$Lambda$5452/1514982901.get(Unknown Source)
	at net.minecraft.class_2614.method_11243(class_2614.java:125)
	at net.minecraft.class_2614.method_16896(class_2614.java:109)
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:424)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:868)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808)
	at net.minecraft.class_1132.method_3748(class_1132.java:92)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at net.minecraft.server.MinecraftServer$$Lambda$4486/411990170.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: The given interface net.minecraft.class_3954 is a superclass/superinterface of the base class class net.minecraft.class_2248 - which won't work very well, because it will override everything else.
	at alexiil.mc.lib.attributes.AdderList.putClassBased(AdderList.java:220)
	at alexiil.mc.lib.attributes.Attribute.putBlockClassAdder(Attribute.java:239)
	at alexiil.mc.lib.attributes.item.ItemAttributes.create(ItemAttributes.java:146)
	at alexiil.mc.lib.attributes.item.ItemAttributes.<clinit>(ItemAttributes.java:89)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at alexiil.mc.lib.attributes.item.mixin.HopperHooks.tryExtract(HopperHooks.java:87)
	at net.minecraft.class_2614.handler$zzp000$onExtract(class_2614.java:538)
	at net.minecraft.class_2614.method_11241(class_2614.java)
	at net.minecraft.class_2614.method_11249(class_2614.java:109)
	at net.minecraft.class_2614$$Lambda$5452/1514982901.get(Unknown Source)
	at net.minecraft.class_2614.method_11243(class_2614.java:125)
	at net.minecraft.class_2614.method_16896(class_2614.java:109)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.class_2614
	Block: Block{minecraft:hopper}[enabled=true,facing=down]
	Block location: World: (-235,64,198), Chunk: (at 5,4,6 in -15,12; contains blocks -240,0,192 to -225,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Block: Block{minecraft:hopper}[enabled=true,facing=down]
	Block location: World: (-235,64,198), Chunk: (at 5,4,6 in -15,12; contains blocks -240,0,192 to -225,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:424)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Avemado'/242, l='ServerLevel[New World]', x=-232.50, y=64.00, z=200.50]]
	Chunk stats: ServerChunkCache: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (-240,63,192), Chunk: (at 0,3,0 in -15,12; contains blocks -240,0,192 to -225,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 334 game time, 334 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 171265 (now: false), thunder time: 93508 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:868)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808)
	at net.minecraft.class_1132.method_3748(class_1132.java:92)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at net.minecraft.server.MinecraftServer$$Lambda$4486/411990170.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1551563232 bytes (1479 MB) / 2136473600 bytes (2037 MB) up to 4772593664 bytes (4551 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5120m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.2
		cardinal-components-base: Cardinal Components API (base) 2.5.4
		cardinal-components-item: Cardinal Components API (items) 2.5.4
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.1
		fabric: Fabric API 0.25.0+build.415-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
		fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a95
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a95
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a95
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab95
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a95
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a95
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a95
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a95
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a95
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
		fabricloader: Fabric Loader 0.10.6+build.214
		inmis: Inmis 1.3.1-1.16.2
		jankson: Jankson 3.0.1+j1.2.0
		jumploader: Jumploader 2.0.1
		libblockattributes: LibBlockAttributes 0.8.0-pre.18
		libblockattributes_core: LibBlockAttributes (Core) 0.8.0-pre.18
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.0-pre.18
		libblockattributes_items: LibBlockAttributes (Items) 0.8.0-pre.18
		libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
		minecraft: Minecraft 1.16.3
		plantinajar: Plant In A Jar 1.8.0
		universalcomponents: Universal Components 0.7.3+1.16.2
	Player Count: 1 / 8; [class_3222['Avemado'/242, l='ServerLevel[New World]', x=-232.50, y=64.00, z=200.50]]
	Data Packs: vanilla (incompatible), fabric/plantinajar, fabric/fabric-tool-attribute-api-v1, fabric/inmis
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by CoolMineman** [comment]
Looks like I need to update LBA

**Comment by CoolMineman** [comment]
Let me know if the issue still happens in the new update

**Comment by Avemado** [comment]
Frickin' awesome! You're a true legend! Thanks a lot!
Awesome ass mod by the way!
